branches:
  only:
  - master
language: ruby
services:
- docker
script:
- make build || exit 1
after_success:
- |
  [ "${TRAVIS_BRANCH}" == "master" ] && [ "$TRAVIS_EVENT_TYPE" != "cron" ] &&
    (make release DOCKER_USER=$DOCKER_USER DOCKER_PASS=$DOCKER_PASS)
notifications:
  slack:
    secure: WX2ERJUrfatoUinPwmSBa2WUO84VadZ3FL7bX7Ts0eMhr16FAqoghKFyZFpqLiJ+idJzzB/OqioNfNHwttD81zJSTfDpz166s5dAibCa9jNRUAzzkl/vwmNWXnVL/7xrd1m5OtXpC8N/z1LxkK5ws9FWmpihJzfx0Y8KuohSCBQSlC6hkgj/VKE9xLBQ3Za3JQvAC5oECKVs+VE3ziRDpOuwMZFKwtcf/hWbCUy43vk64wJDnpbwYHE/PVQKBQEglGK6+ocmc+X5IRmCkSvL/oHe4ukOt0xF3K7ruoNnEC7YCd3t0Qq78WhD9aMc8CjF04uljF+ODikNbGgyobG/wXT7K7fvT0BGbsFgOOkkyTOjAVSlrpkNQsTa87YXT0vb6zcZ4HzC5qTjFFPtIuH30Py1UXpK9+iFcjhUutgipeoND9ph4c7HA0dGeU86+1NCkINmGOQYrZsuDv9NevEFLyzuirXmk6TtBnKKWLR6TW8Tdv/QESpaGgxopxBjQfEWeAkAm9MUY1g8dHiSCmmXEvvyJQTB6HjCvzcqiU7/tOgzUi6LA8lYlZzeQ1RXjad2jhyDdjEuKL3NaScIu0+/MsHql4k6a+MOxNSt5sQk2i4SWO4Cqj6ziCUOU2WHHVRWAmSqSpsETvrd/EmEwFXX4H+Dh/HoiU8nFi2Yi4aIuxo=
